name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP Laravel
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.mysql

      - name: Execute tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: database/database.mysql
        run: php artisan test

      # 3. SSH into EC2 & Deploy with Docker Compose
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            cd /home/ubuntu/testProject

            # GitHub se latest code pull karein taaki docker-compose aur nginx ki config update ho jaye
            git pull origin main

            # Purane containers ko band karke docker-compose se Nginx + PHP dono ko ek sath build aur start karein
            docker compose down
            docker compose up -d --build
